create table if not exists public.world_cup_public_evidence (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('fixture', 'market')),
  content_hash text not null,
  match_id text,
  source text not null,
  captured_at timestamptz not null,
  source_updated_at timestamptz,
  schema_version integer not null check (schema_version > 0),
  payload jsonb not null,
  created_at timestamptz not null default now(),
  constraint world_cup_public_evidence_hash_unique unique (kind, content_hash),
  constraint world_cup_market_evidence_has_match
    check (kind <> 'market' or match_id is not null)
);

create or replace function public.prevent_world_cup_public_evidence_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception 'World Cup public evidence is append-only.';
end;
$$;

drop trigger if exists prevent_world_cup_public_evidence_mutation
  on public.world_cup_public_evidence;
create trigger prevent_world_cup_public_evidence_mutation
before update or delete on public.world_cup_public_evidence
for each row execute function public.prevent_world_cup_public_evidence_mutation();

alter table public.world_cup_public_evidence enable row level security;

revoke all on table public.world_cup_public_evidence from anon, authenticated;
grant select on table public.world_cup_public_evidence to anon, authenticated;

drop policy if exists "World Cup public evidence is readable"
  on public.world_cup_public_evidence;
create policy "World Cup public evidence is readable"
on public.world_cup_public_evidence
for select
to anon, authenticated
using (true);

create index if not exists world_cup_public_evidence_captured_idx
  on public.world_cup_public_evidence (captured_at desc);
create index if not exists world_cup_public_evidence_match_idx
  on public.world_cup_public_evidence (match_id, captured_at desc)
  where match_id is not null;
