create table if not exists public.world_cup_client_telemetry (
  id bigint generated by default as identity primary key,
  schema_version integer not null check (schema_version = 1),
  kind text not null check (kind in ('web-vital', 'runtime-error')),
  name text not null,
  value double precision,
  rating text,
  fingerprint text,
  route text not null check (
    route in ('main', 'traditional', 'sports', 'football', 'world-cup', 'game', 'unknown')
  ),
  navigation_type text not null check (
    navigation_type in ('navigate', 'reload', 'back-forward', 'prerender', 'unknown')
  ),
  received_at timestamptz not null,
  dedupe_key text not null unique,
  created_at timestamptz not null default now(),
  constraint world_cup_client_telemetry_payload_check check (
    (
      kind = 'web-vital'
      and name in ('CLS', 'INP', 'LCP')
      and value is not null
      and value >= 0
      and (
        (name = 'CLS' and value <= 100)
        or (name in ('INP', 'LCP') and value <= 3600000)
      )
      and rating in ('good', 'needs-improvement', 'poor')
      and fingerprint is null
    )
    or
    (
      kind = 'runtime-error'
      and name in ('window-error', 'unhandled-rejection', 'react-error')
      and value is null
      and rating is null
      and fingerprint ~ '^[0-9a-f]{64}$'
    )
  )
);

alter table public.world_cup_client_telemetry enable row level security;

revoke all on table public.world_cup_client_telemetry from anon, authenticated;

create index if not exists world_cup_client_telemetry_received_idx
  on public.world_cup_client_telemetry (received_at desc);
create index if not exists world_cup_client_telemetry_kind_name_idx
  on public.world_cup_client_telemetry (kind, name, received_at desc);
